-- TruHoldem schema baseline (Postgres). Generated from the JPA entities via Hibernate ddl-auto=create,
-- then captured with pg_dump --schema-only. This is the single source of truth for the schema; the
-- pre-baseline incremental changelogs were squashed into it (see db/changelog/archive/).
-- Liquibase only targets Postgres in this project (tests use H2 + Hibernate), so raw SQL is fine.

CREATE TABLE public.achievements (
    id uuid NOT NULL,
    category character varying(255),
    code character varying(255) NOT NULL,
    description character varying(255),
    icon character varying(255),
    is_hidden boolean NOT NULL,
    name character varying(255) NOT NULL,
    points integer NOT NULL,
    requirement_type character varying(255),
    requirement_value integer NOT NULL
);
CREATE TABLE public.game_community_cards (
    game_id uuid NOT NULL,
    suit character varying(255),
    card_value character varying(255),
    community_cards_order integer NOT NULL,
    CONSTRAINT game_community_cards_card_value_check CHECK (((card_value)::text = ANY ((ARRAY['TWO'::character varying, 'THREE'::character varying, 'FOUR'::character varying, 'FIVE'::character varying, 'SIX'::character varying, 'SEVEN'::character varying, 'EIGHT'::character varying, 'NINE'::character varying, 'TEN'::character varying, 'JACK'::character varying, 'QUEEN'::character varying, 'KING'::character varying, 'ACE'::character varying])::text[]))),
    CONSTRAINT game_community_cards_suit_check CHECK (((suit)::text = ANY ((ARRAY['HEARTS'::character varying, 'DIAMONDS'::character varying, 'CLUBS'::character varying, 'SPADES'::character varying])::text[])))
);
CREATE TABLE public.game_deck (
    game_id uuid NOT NULL,
    suit character varying(255),
    card_value character varying(255),
    deck_order integer NOT NULL,
    CONSTRAINT game_deck_card_value_check CHECK (((card_value)::text = ANY ((ARRAY['TWO'::character varying, 'THREE'::character varying, 'FOUR'::character varying, 'FIVE'::character varying, 'SIX'::character varying, 'SEVEN'::character varying, 'EIGHT'::character varying, 'NINE'::character varying, 'TEN'::character varying, 'JACK'::character varying, 'QUEEN'::character varying, 'KING'::character varying, 'ACE'::character varying])::text[]))),
    CONSTRAINT game_deck_suit_check CHECK (((suit)::text = ANY ((ARRAY['HEARTS'::character varying, 'DIAMONDS'::character varying, 'CLUBS'::character varying, 'SPADES'::character varying])::text[])))
);
CREATE TABLE public.game_event_log (
    seq_no bigint NOT NULL,
    event_id uuid NOT NULL,
    event_type character varying(64) NOT NULL,
    game_id uuid NOT NULL,
    hand_number integer NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    payload oid NOT NULL
);
ALTER TABLE public.game_event_log ALTER COLUMN seq_no ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_event_log_seq_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.game_missed_blinds (
    game_id uuid NOT NULL,
    missed_amount integer,
    seat_position integer NOT NULL
);
CREATE TABLE public.game_winner_ids (
    game_id uuid NOT NULL,
    winner_ids uuid
);
CREATE TABLE public.hand_histories (
    id uuid NOT NULL,
    big_blind integer NOT NULL,
    dealer_position integer NOT NULL,
    final_pot integer NOT NULL,
    game_id uuid NOT NULL,
    hand_number integer NOT NULL,
    played_at timestamp(6) without time zone NOT NULL,
    small_blind integer NOT NULL,
    winner_name character varying(255),
    winning_hand_description character varying(255)
);
CREATE TABLE public.hand_history_actions (
    hand_history_id uuid NOT NULL,
    player_id uuid,
    player_name character varying(255),
    action character varying(255),
    amount integer,
    phase character varying(255),
    "timestamp" timestamp(6) without time zone,
    action_order integer NOT NULL
);
CREATE TABLE public.hand_history_board (
    hand_history_id uuid NOT NULL,
    suit character varying(255),
    card_value character varying(255),
    card_order integer NOT NULL
);
CREATE TABLE public.hand_history_players (
    hand_history_id uuid NOT NULL,
    hole_card1suit character varying(255),
    hole_card1value character varying(255),
    hole_card2suit character varying(255),
    hole_card2value character varying(255),
    player_id uuid,
    player_name character varying(255),
    seat_position integer,
    starting_chips integer
);
CREATE TABLE public.player_achievements (
    id uuid NOT NULL,
    progress integer NOT NULL,
    unlocked_at timestamp(6) without time zone NOT NULL,
    achievement_id uuid NOT NULL,
    player_stats_id uuid NOT NULL
);
CREATE TABLE public.player_hand (
    player_id uuid NOT NULL,
    suit character varying(255),
    card_value character varying(255),
    hand_order integer NOT NULL,
    CONSTRAINT player_hand_card_value_check CHECK (((card_value)::text = ANY ((ARRAY['TWO'::character varying, 'THREE'::character varying, 'FOUR'::character varying, 'FIVE'::character varying, 'SIX'::character varying, 'SEVEN'::character varying, 'EIGHT'::character varying, 'NINE'::character varying, 'TEN'::character varying, 'JACK'::character varying, 'QUEEN'::character varying, 'KING'::character varying, 'ACE'::character varying])::text[]))),
    CONSTRAINT player_hand_suit_check CHECK (((suit)::text = ANY ((ARRAY['HEARTS'::character varying, 'DIAMONDS'::character varying, 'CLUBS'::character varying, 'SPADES'::character varying])::text[])))
);
CREATE TABLE public.player_statistics (
    id uuid NOT NULL,
    all_ins_won integer NOT NULL,
    biggest_pot_won integer NOT NULL,
    current_lose_streak integer NOT NULL,
    current_win_streak integer NOT NULL,
    first_hand_played timestamp(6) without time zone,
    hands_played integer NOT NULL,
    hands_played_from_blinds integer NOT NULL,
    hands_played_from_button integer NOT NULL,
    hands_raised_pre_flop integer NOT NULL,
    hands_voluntarily_put_in_pot integer NOT NULL,
    hands_went_to_showdown integer NOT NULL,
    hands_won integer NOT NULL,
    last_hand_played timestamp(6) without time zone,
    longest_lose_streak integer NOT NULL,
    longest_win_streak integer NOT NULL,
    player_name character varying(255) NOT NULL,
    showdowns_won integer NOT NULL,
    times_all_in integer NOT NULL,
    total_bets integer NOT NULL,
    total_calls integer NOT NULL,
    total_checks integer NOT NULL,
    total_folds integer NOT NULL,
    total_losses numeric(38,2),
    total_raises integer NOT NULL,
    total_sessions integer NOT NULL,
    total_winnings numeric(38,2),
    user_id uuid
);
CREATE TABLE public.players (
    id uuid NOT NULL,
    bet_amount integer NOT NULL,
    chips integer NOT NULL,
    has_acted boolean NOT NULL,
    is_all_in boolean NOT NULL,
    is_bot boolean NOT NULL,
    is_folded boolean NOT NULL,
    name character varying(255),
    seat_position integer NOT NULL,
    total_bet_in_round integer NOT NULL,
    user_id uuid,
    version bigint,
    game_id uuid
);
CREATE TABLE public.poker_games (
    id uuid NOT NULL,
    big_blind integer NOT NULL,
    button_seat_position integer NOT NULL,
    created_at timestamp(6) with time zone,
    current_bet integer NOT NULL,
    current_player_index integer NOT NULL,
    current_pot integer NOT NULL,
    dead_button boolean NOT NULL,
    dealer_position integer NOT NULL,
    hand_lifecycle_state character varying(255),
    hand_number integer NOT NULL,
    is_finished boolean NOT NULL,
    last_aggressor_id uuid,
    last_raise_amount integer NOT NULL,
    min_raise_amount integer NOT NULL,
    phase character varying(255),
    small_blind integer NOT NULL,
    updated_at timestamp(6) with time zone,
    version bigint,
    winner_name character varying(255),
    winning_hand_description character varying(255),
    CONSTRAINT poker_games_hand_lifecycle_state_check CHECK (((hand_lifecycle_state)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'HAND_COMPLETED'::character varying, 'RESULT_DELAY'::character varying, 'NEXT_HAND'::character varying])::text[]))),
    CONSTRAINT poker_games_phase_check CHECK (((phase)::text = ANY ((ARRAY['PRE_FLOP'::character varying, 'FLOP'::character varying, 'TURN'::character varying, 'RIVER'::character varying, 'SHOWDOWN'::character varying, 'FINISHED'::character varying])::text[])))
);
CREATE TABLE public.refresh_tokens (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id uuid NOT NULL
);
CREATE TABLE public.roles (
    id uuid NOT NULL,
    description character varying(255),
    name character varying(50) NOT NULL
);
CREATE TABLE public.side_pots (
    id bigint NOT NULL,
    amount integer NOT NULL,
    contribution_per_player integer NOT NULL,
    game_id uuid
);
ALTER TABLE public.side_pots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.side_pots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sidepot_eligible_players (
    sidepot_id bigint NOT NULL,
    player_id uuid
);
CREATE TABLE public.tournament_blind_levels (
    tournament_id uuid NOT NULL,
    ante integer,
    big_blind integer,
    level integer,
    small_blind integer,
    level_order integer NOT NULL
);
CREATE TABLE public.tournament_payout_structure (
    tournament_id uuid NOT NULL,
    percentage integer,
    position_order integer NOT NULL
);
CREATE TABLE public.tournament_registrations (
    id uuid NOT NULL,
    add_ons_used integer NOT NULL,
    bounties_collected integer NOT NULL,
    bounty_value integer NOT NULL,
    current_chips integer NOT NULL,
    eliminated_at timestamp(6) with time zone,
    finish_position integer,
    player_id uuid NOT NULL,
    player_name character varying(255) NOT NULL,
    prize_won integer NOT NULL,
    rebuys_used integer NOT NULL,
    registered_at timestamp(6) with time zone NOT NULL,
    started_playing_at timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    version bigint,
    tournament_id uuid NOT NULL,
    CONSTRAINT tournament_registrations_status_check CHECK (((status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'PLAYING'::character varying, 'ELIMINATED'::character varying, 'FINISHED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);
CREATE TABLE public.tournament_table_players (
    table_id uuid NOT NULL,
    player_id uuid,
    seat_position integer NOT NULL
);
CREATE TABLE public.tournament_tables (
    id uuid NOT NULL,
    closed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    is_active boolean NOT NULL,
    is_final_table boolean NOT NULL,
    table_number integer NOT NULL,
    version bigint,
    current_game_id uuid,
    tournament_id uuid NOT NULL
);
CREATE TABLE public.tournaments (
    id uuid NOT NULL,
    add_on_amount integer NOT NULL,
    level_duration_minutes integer,
    bounty_amount integer NOT NULL,
    buy_in integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    current_level integer NOT NULL,
    end_time timestamp(6) with time zone,
    hands_per_round integer NOT NULL,
    level_start_time timestamp(6) with time zone,
    max_players integer NOT NULL,
    max_rebuys integer NOT NULL,
    min_players integer NOT NULL,
    name character varying(255) NOT NULL,
    pyramid_round integer NOT NULL,
    rebuy_amount integer NOT NULL,
    rebuy_deadline_level integer NOT NULL,
    seats_per_table integer NOT NULL,
    start_time timestamp(6) with time zone,
    starting_chips integer NOT NULL,
    status character varying(255) NOT NULL,
    tournament_type character varying(255) NOT NULL,
    version bigint,
    CONSTRAINT tournaments_status_check CHECK (((status)::text = ANY ((ARRAY['REGISTERING'::character varying, 'STARTING'::character varying, 'LATE_REGISTRATION'::character varying, 'RUNNING'::character varying, 'PAUSED'::character varying, 'FINAL_TABLE'::character varying, 'HEADS_UP'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT tournaments_tournament_type_check CHECK (((tournament_type)::text = ANY ((ARRAY['FREEZEOUT'::character varying, 'REBUY'::character varying, 'BOUNTY'::character varying, 'SIT_AND_GO'::character varying, 'MULTI_TABLE'::character varying, 'PYRAMID'::character varying])::text[])))
);
CREATE TABLE public.user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL
);
CREATE TABLE public.users (
    id uuid NOT NULL,
    avatar_url character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(100) NOT NULL,
    first_name character varying(50),
    is_active boolean NOT NULL,
    is_email_verified boolean NOT NULL,
    last_login timestamp(6) with time zone,
    last_name character varying(50),
    oauth_id character varying(255),
    oauth_provider character varying(20),
    password_hash character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT users_oauth_provider_check CHECK (((oauth_provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'GITHUB'::character varying])::text[])))
);
ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.game_community_cards
    ADD CONSTRAINT game_community_cards_pkey PRIMARY KEY (game_id, community_cards_order);
ALTER TABLE ONLY public.game_deck
    ADD CONSTRAINT game_deck_pkey PRIMARY KEY (game_id, deck_order);
ALTER TABLE ONLY public.game_event_log
    ADD CONSTRAINT game_event_log_pkey PRIMARY KEY (seq_no);
ALTER TABLE ONLY public.game_missed_blinds
    ADD CONSTRAINT game_missed_blinds_pkey PRIMARY KEY (game_id, seat_position);
ALTER TABLE ONLY public.hand_histories
    ADD CONSTRAINT hand_histories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.hand_history_actions
    ADD CONSTRAINT hand_history_actions_pkey PRIMARY KEY (hand_history_id, action_order);
ALTER TABLE ONLY public.hand_history_board
    ADD CONSTRAINT hand_history_board_pkey PRIMARY KEY (hand_history_id, card_order);
ALTER TABLE ONLY public.game_event_log
    ADD CONSTRAINT idx_game_event_log_event_id UNIQUE (event_id);
ALTER TABLE ONLY public.player_achievements
    ADD CONSTRAINT player_achievements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.player_hand
    ADD CONSTRAINT player_hand_pkey PRIMARY KEY (player_id, hand_order);
ALTER TABLE ONLY public.player_statistics
    ADD CONSTRAINT player_statistics_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.poker_games
    ADD CONSTRAINT poker_games_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.side_pots
    ADD CONSTRAINT side_pots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tournament_blind_levels
    ADD CONSTRAINT tournament_blind_levels_pkey PRIMARY KEY (tournament_id, level_order);
ALTER TABLE ONLY public.tournament_payout_structure
    ADD CONSTRAINT tournament_payout_structure_pkey PRIMARY KEY (tournament_id, position_order);
ALTER TABLE ONLY public.tournament_registrations
    ADD CONSTRAINT tournament_registrations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tournament_table_players
    ADD CONSTRAINT tournament_table_players_pkey PRIMARY KEY (table_id, seat_position);
ALTER TABLE ONLY public.tournament_tables
    ADD CONSTRAINT tournament_tables_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tournaments
    ADD CONSTRAINT tournaments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT uk9qqq83lafche8dr9o229kc9tg UNIQUE (code);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);
ALTER TABLE ONLY public.player_achievements
    ADD CONSTRAINT uki1pf8ifofnktb2pks3liejtqq UNIQUE (player_stats_id, achievement_id);
ALTER TABLE ONLY public.tournament_tables
    ADD CONSTRAINT ukn5gu7gbu3ueb5mos6f48rs4qp UNIQUE (current_game_id);
ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);
ALTER TABLE ONLY public.player_statistics
    ADD CONSTRAINT ukoyskv9r3jdswksfxxsqw3x0jt UNIQUE (user_id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE INDEX idx_game_created_at ON public.poker_games USING btree (created_at);
CREATE INDEX idx_game_event_log_game ON public.game_event_log USING btree (game_id);
CREATE INDEX idx_game_event_log_game_hand ON public.game_event_log USING btree (game_id, hand_number, seq_no);
CREATE INDEX idx_game_finished ON public.poker_games USING btree (is_finished);
CREATE INDEX idx_game_phase ON public.poker_games USING btree (phase);
CREATE INDEX idx_hand_history_game ON public.hand_histories USING btree (game_id);
CREATE INDEX idx_hand_history_played_at ON public.hand_histories USING btree (played_at);
CREATE INDEX idx_player_stats_name ON public.player_statistics USING btree (player_name);
CREATE INDEX idx_player_stats_user ON public.player_statistics USING btree (user_id);
CREATE INDEX idx_reg_player ON public.tournament_registrations USING btree (player_id);
CREATE INDEX idx_reg_position ON public.tournament_registrations USING btree (finish_position);
CREATE INDEX idx_reg_status ON public.tournament_registrations USING btree (status);
CREATE INDEX idx_reg_tournament ON public.tournament_registrations USING btree (tournament_id);
CREATE INDEX idx_tournament_start ON public.tournaments USING btree (start_time);
CREATE INDEX idx_tournament_status ON public.tournaments USING btree (status);
CREATE INDEX idx_tournament_table_number ON public.tournament_tables USING btree (table_number);
CREATE INDEX idx_tournament_table_tournament ON public.tournament_tables USING btree (tournament_id);
CREATE INDEX idx_tournament_type ON public.tournaments USING btree (tournament_type);
ALTER TABLE ONLY public.player_achievements
    ADD CONSTRAINT fk143ynai7255amy76nfd5ballh FOREIGN KEY (player_stats_id) REFERENCES public.player_statistics(id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.game_missed_blinds
    ADD CONSTRAINT fk1qqbrkr6mfvjmgb6hxub7edf2 FOREIGN KEY (game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.tournament_registrations
    ADD CONSTRAINT fk2mpg0cs7jn7a10v34nhmg03lg FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id);
ALTER TABLE ONLY public.player_hand
    ADD CONSTRAINT fk31rjad2pfe31t2t25ji6oq190 FOREIGN KEY (player_id) REFERENCES public.players(id);
ALTER TABLE ONLY public.tournament_table_players
    ADD CONSTRAINT fk4kmkgmxdou8w48f3ryllwf8f3 FOREIGN KEY (table_id) REFERENCES public.tournament_tables(id);
ALTER TABLE ONLY public.tournament_tables
    ADD CONSTRAINT fk820esd1g1iahgvrxd1e12md2f FOREIGN KEY (current_game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.tournament_blind_levels
    ADD CONSTRAINT fk8k82mv3wxw7ct08o40kv8djas FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id);
ALTER TABLE ONLY public.player_achievements
    ADD CONSTRAINT fk93bwsp0dmcs7rclg5v80mx2e7 FOREIGN KEY (achievement_id) REFERENCES public.achievements(id);
ALTER TABLE ONLY public.tournament_tables
    ADD CONSTRAINT fkb50jcla01krm9fb8jxlsg839i FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id);
ALTER TABLE ONLY public.side_pots
    ADD CONSTRAINT fkb7old9gicdu9haigytv2n1yrc FOREIGN KEY (game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.hand_history_actions
    ADD CONSTRAINT fkcg3lo5kqigdxjd29ji8baanjs FOREIGN KEY (hand_history_id) REFERENCES public.hand_histories(id);
ALTER TABLE ONLY public.players
    ADD CONSTRAINT fkejn24ooroymyk9cpm9dhhhovw FOREIGN KEY (game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.hand_history_players
    ADD CONSTRAINT fkeu9v68qs1n6j5wofvhbnqx371 FOREIGN KEY (hand_history_id) REFERENCES public.hand_histories(id);
ALTER TABLE ONLY public.game_winner_ids
    ADD CONSTRAINT fkfp4rbtv5e57rb1krnpx8nxy2e FOREIGN KEY (game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.game_community_cards
    ADD CONSTRAINT fkh1jwwom289ghgblernx1lb1b4 FOREIGN KEY (game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);
ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.hand_history_board
    ADD CONSTRAINT fkhqnjwjqtjlefun82vdknrgelx FOREIGN KEY (hand_history_id) REFERENCES public.hand_histories(id);
ALTER TABLE ONLY public.game_deck
    ADD CONSTRAINT fkmafso5r2mddda503cbq98y0h8 FOREIGN KEY (game_id) REFERENCES public.poker_games(id);
ALTER TABLE ONLY public.sidepot_eligible_players
    ADD CONSTRAINT fkolf4x0sf0kbowr3rcr4qjccj7 FOREIGN KEY (sidepot_id) REFERENCES public.side_pots(id);
ALTER TABLE ONLY public.tournament_payout_structure
    ADD CONSTRAINT fkq57xe1w7g84fon2qbs6dol7gh FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id);

-- Robustness: one statistics row per player name (get-or-create keys on player_name).
ALTER TABLE ONLY public.player_statistics
    ADD CONSTRAINT uq_player_stats_player_name UNIQUE (player_name);
