apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: truholdem-backend-hpa
  namespace: truholdem-pyramid
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: truholdem-backend
  minReplicas: 8
  maxReplicas: 16
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
